# Produce tile geometries based on the AoI extent and zoom level
prepare_data.py:  
  srs: "EPSG:2056"
  datasets:
    shapefile: ./data/AoI/<AOI_SHPFILE> 
  output_folder: ./output/det/
  zoom_level: 20 


# Fetch of tiles (online server) and split into 3 datasets: train, test, validation
generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 2000
  working_directory: .
  datasets:
    aoi_tiles: ./output/det/tiles.geojson
    image_source:
      type: XYZ                             # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ 4. FOLDER
      year: 2022                  # supported values: 1. multi-year (tiles of different year), 2. <year> (i.e. 2020)
      location: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/{year}/3857/{z}/{x}/{y}.jpeg
  output_folder: ./output/det/
  tile_size: 256      # per side, in pixels
  overwrite: True
  n_jobs: 10
  seed: 2
  COCO_metadata:
    year: 2024
    version: 1.0
    description: Energy facilities
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: unknown
      url: unknown
    categories_file: ./data/category_ids.json


# Object detection with the optimised trained model
make_detections.py:
  working_directory: ./output/det/
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    oth: COCO_oth.json
  detectron2_config_file: ../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: ../../models/model_0002999.pth # trained model minimising the validation loss curve, monitor the training process via tensorboard (tensorboard --logdir </logs>)
  image_metadata_json: img_metadata.json
  rdp_simplification:   # rdp = Ramer-Douglas-Peucker
    enabled: true
    epsilon: 2.0        # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05
  remove_det_overlap: True  # if several detections overlap (IoU > 0.5), only the one with the highest confidence score is retained


post-processing.py:
  year: 2023
  detections: ./output/output_det/oth_detections_at_0dot05_threshold.gpkg
  score: 0.90 # detection score (from 0 to 1) provided by detectron2
  distance: 0.2 # m, distance use as a buffer to merge close polygons (likely to belong to the same object) together
  area: 1.0 # m2, area threshold under which polygons are discarded
  output: ./output/output_det/oth_detections_at_0dot05_threshold_year-{year}_score-{score}_area-{area}_distance-{distance}.gpkg

# Assess the final results
merge_detections.py:
  working_dir: ./output/det/
  detections:
    oth: oth_detections_at_0dot05_threshold.gpkg
  distance: 10 # m, distance use as a buffer to merge close polygons (likely to belong to the same object) together
  iou_threshold: 0.1
  score_threshold: 0.05
  assess: 
    enable: False
    metrics_method: macro-average   # 1: macro-average ; 2: macro-weighted-average ; 3: micro-average
  

result_review.py:
  file: ./input/<SHP_FILE>
  output: ./output/output_det/