prepare_data.py:  
  srs: "EPSG:2056"
  datasets:
    shapefile: ./input/input_det/<SHP_FILE>
  output_folder: ./output/output_det/
  zoom_level: 20 

generate_tilesets.py:
  debug_mode:
    enable: True  # sample of tiles
    nb_tiles_max: 100
  working_directory: output
  datasets:
    aoi_tiles: ./output/output_det/tiles.geojson
    image_source:
      type: XYZ # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ
      location: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/current/3857/{z}/{x}/{y}.jpeg
  output_folder: ./output/output_det/
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2021
    version: 1.0
    description: Swiss Image Hinterground w/ Thermal panel detection
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: Unknown
      url:

make_detections.py:
  working_directory: ./output/output_det/
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files: # relative paths, w/ respect to the working_directory
    oth: COCO_oth.json
  detectron2_config_file: '../../config/detectron2_config_tpnl.yaml' # path relative to the working_directory
  model_weights:
    pth_file: '../output_trne/logs/model_<*>.pth'
  image_metadata_json: 'img_metadata.json'
  rdp_simplification: # rdp = Ramer-Douglas-Peucker
    enabled: False
    epsilon: 0.5 # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05

post-processing.py:
  year: 2023
  detections: ./output/output_det/oth_detections_at_0dot05_threshold.gpkg
  score: 0.90 # detection score (from 0 to 1) provided by detectron2
  distance: 0.2 # m, distance use as a buffer to merge close polygons (likely to belong to the same object) together
  area: 1.0 # m2, area threshold under which polygons are discarded
  output: ./output/output_det/oth_detections_at_0dot05_threshold_year-{year}_score-{score}_area-{area}_distance-{distance}.gpkg

result_review.py:
  file: ./input/<SHP_FILE>
  output: ./output/output_det/