prepare_data.py:
  srs: "EPSG:2056"
  tiling:
    csv: ../input/NE/20210330-input-labelled-tile-nh-hr-correction.csv
    # shapefile: ../input/NE/tiles_256_0_0.shp
    #csv: [TILE_CSV_FILE]
    split: 1
  label:
    shapefile: ../input/NE/20210330-input-label-nh-hr-correction.shp
    redfact: 0.9
  output_folder: ../output/output-tpnl

generate_tilesets.py:
  debug_mode: False
  datasets:
    aoi_tiles_geojson: ../output/output-tpnl/tiles.geojson
    ground_truth_labels_geojson: ../output/output-tpnl/labels.geojson
    orthophotos_web_service:
      type: WMS # supported values: 1. MIL = Map Image Layer 2. WMS
      url: https://wms.geo.admin.ch/service
      layers: ch.swisstopo.swissimage
      srs: "EPSG:2056"
  output_folder: ../output/output-tpnl
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2021
    version: 1.0
    description: Swiss Image Hinterground w/ Thermal panel detection
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: Unknown
      url:
    category:
        name: "Thermal Panel"
        supercategory: "Infrastructure"

train_model.py:
    working_folder: ../output/output-tpnl
    log_subfolder: logs
    sample_tagged_img_subfolder: sample_tagged_images
    COCO_files: # relative paths, w/ respect to the working_folder
        trn: COCO_trn.json
        val: COCO_val.json
        tst: COCO_tst.json
    detectron2_config_file: '../../config/detectron2_config_tpnl.yaml' # path relative to the working_folder
    model_weights:
        model_zoo_checkpoint_url: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"

make_predictions.py:
    working_folder: ../output/output-tpnl
    log_subfolder: logs
    sample_tagged_img_subfolder: sample_tagged_images
    COCO_files: # relative paths, w/ respect to the working_folder
        trn: COCO_trn.json
        val: COCO_val.json
        tst: COCO_tst.json
    detectron2_config_file: '../../config/detectron2_config_tpnl.yaml' # path relative to the working_folder
    model_weights:
        pth_file: './logs/model_0004999.pth'
    image_metadata_json: '../output/output-tpnl/img_metadata.json'
    rdp_simplification: # rdp = Ramer-Douglas-Peucker
      enabled: false
      epsilon: 0.5 # cf. https://rdp.readthedocs.io/en/latest/
    score_lower_threshold: 0.05
  
assess_predictions.py:
  datasets:
    ground_truth_labels_geojson: ../output/output-tpnl/labels.geojson
    image_metadata_json: ../output/output-tpnl/img_metadata.json
    split_aoi_tiles_geojson: ../output/output-tpnl/split_aoi_tiles.geojson # aoi = Area of Interest
    predictions:
      trn: ../output/output-tpnl/trn_predictions_at_0dot05_threshold.gpkg
      val: ../output/output-tpnl/val_predictions_at_0dot05_threshold.gpkg
      tst: ../output/output-tpnl/tst_predictions_at_0dot05_threshold.gpkg
  output_folder: ../output/output-tpnl
