prepare_data.py:  
  srs: "EPSG:2056"
  datasets:
    shapefile: ./input/input_trne/<SHP_FILE>
  output_folder: ./output/output_trne/
  zoom_level: 20 

generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 50
  working_directory: output
  datasets:
    aoi_tiles: ./output_trne/tiles.geojson
    ground_truth_labels: ./output_trne/labels.geojson
    image_source:
      type: XYZ # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ
      location: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/<YEAR>/3857/{z}/{x}/{y}.jpeg
  output_folder: ./output_trne/
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2021
    version: 1.0
    description: Swiss Image Hinterground w/ Thermal panel detection
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: Unknown
      url:

train_model.py:
    working_directory: ./output/output_trne/
    log_subfolder: logs
    sample_tagged_img_subfolder: sample_tagged_images
    COCO_files: # relative paths, w/ respect to the working_directory
      trn: COCO_trn.json
      val: COCO_val.json
      tst: COCO_tst.json
    detectron2_config_file: '../../config/detectron2_config_tpnl.yaml' # path relative to the working_folder 202
    model_weights:
      model_zoo_checkpoint_url: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"

make_detections.py:
  working_directory: ./output/output_trne/
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files: # relative paths, w/ respect to the working_directory
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: '../../config/detectron2_config_tpnl.yaml' # path relative to the working_folder
  model_weights:
    pth_file: './logs/model_<*>.pth'
  image_metadata_json: 'img_metadata.json'
  rdp_simplification: # rdp = Ramer-Douglas-Peucker
    enabled: false
    epsilon: 0.5 # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05

assess_detections.py:
  working_directory: ./output/output_trne
  datasets:
    ground_truth_labels: ./labels.geojson
    image_metadata: ./img_metadata.json
    split_aoi_tiles: ./split_aoi_tiles.geojson # aoi = Area of Interest
    detections:
      trn: ./trn_detections_at_0dot05_threshold.gpkg
      val: ./val_detections_at_0dot05_threshold.gpkg
      tst: ./tst_detections_at_0dot05_threshold.gpkg
  output_folder: .